### ISSUE TITLE
能否做个Docker命令创建的命令呢，运行交互脚本和一键脚本后，只显示了一下SWAP和LINUX信息和版本，就没其它显示和下步了

### ISSUE THREAD

**Issue by wifisky-feilian** [Chasing66/peer2profit#1]
能否做个Docker命令创建的命令呢，运行交互脚本和一键脚本后，只显示了一下SWAP和LINUX信息和版本，就没其它显示和下步了~
[root@NAS peer2profit]# ./peer2fly.sh
Swap already enabled
Filename				Type		Size	Used	Priority
/dev/md8                                partition	999868	313344	-1
              total        used        free      shared  buff/cache   available
Mem:           1.8G        700M         42M         19M        1.1G        1.1G
Swap:          976M        306M        670M
Linux distribution is: nas
Linux version is: 2018.04.9
Unsupported linux system
[root@NAS peer2profit]#

**Comment by enwaiax** [comment]
你的nas是什么操作系统

**Comment by enwaiax** [comment]
No more response, will be closed
