### ISSUE TITLE
Peer2profit Is on but not earning

### ISSUE THREAD

**Issue by marimatt** [Chasing66/peer2profit#16]
Hello, thank you very much for your work.
I successfully readapted a bit your code and I have now the docker peer2profit running, as I can also see it in my dashboard .
The problem is that is not sharing bandwidth, it displays 0 Bites on the "mynetworks" page .
Is now like 4 days that is up and running.
Do you have any idea of why this is happening? 

I'm using a Linux virtual machine , which I'm paying to an host provider monthly for other purposes

**Comment by Goobermas** [comment]
what region is your VM deployed in?

**Comment by enwaiax** [comment]
Yes, it depends on where your VM is located and what kind of bandwidth it is. These located in Russian and especially with residential IP will gain more trafic. 
Actually, it gains a lot last year and now it's quite a alittle.

**Comment by marimatt** [comment]
Hello! Thanks a lot for your engagement.
The server is deployed in Italy, where I have other nodes already, but not on VMs (a phone and a desktop pc, both earning).
The problem was really that 0 Bytes was displayed as shared bandwitdth after around 1 week of uptime.
I was more wondering about the need of opening ports or disabling firewall ecc.ecc.. but i'm not expert in this field

**Comment by enwaiax** [comment]
You can use `docker logs -f <container id>` to check the running logs to see wheter it's running normally.
Usually we are using firewalld or ufw as firewall. You can search on google to see how to disable it but I am not sure whether it can work

**Comment by Goobermas** [comment]
maybe deploy your VM instances somewhere else where there is a higher payout.
