### ISSUE TITLE
how to use it on gcp? 

### ISSUE THREAD

**Issue by xingpingcn** [Chasing66/peer2profit#22]
it can be used on aws but not on gcp
info. about the gcp VM: Intel Broadwell x86/64 [debian-11-bullseye-v20230206]

here are the logs 

Swap already enabled
Filename                                Type            Size            Used            Priority
/swapfile                               file            8048636         0               -2
               total        used        free      shared  buff/cache   available
Mem:           3.8Gi       133Mi       3.4Gi       0.0Ki       363Mi       3.5Gi
Swap:          7.7Gi          0B       7.7Gi
Installing docker
# Executing docker install script, commit: 66474034547a96caa0a25be56051ff8b726a1b28
+ sh -c 'apt-get update -qq >/dev/null'
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.debian.org/debian bullseye InRelease: Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye_InRelease into data and signature failed
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.debian.org/debian bullseye-updates InRelease: Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye-updates_InRelease into data and signature failed
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.debian.org/debian bullseye-backports InRelease: Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye-backports_InRelease into data and signature failed
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt google-compute-engine-bullseye-stable InRelease: Splitting up /var/lib/apt/lists/packages.cloud.google.com_apt_dists_google-compute-engine-bullseye-stable_InRelease into data and signature failed
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt cloud-sdk-bullseye InRelease: Splitting up /var/lib/apt/lists/packages.cloud.google.com_apt_dists_cloud-sdk-bullseye_InRelease into data and signature failed
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye_InRelease into data and signature failed
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Error writing to file - write (28: No space left on device) [IP: 151.101.78.132 80]
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye-updates_InRelease into data and signature failed
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-backports/InRelease  Splitting up /var/lib/apt/lists/deb.debian.org_debian_dists_bullseye-backports_InRelease into data and signature failed
W: Failed to fetch http://packages.cloud.google.com/apt/dists/google-compute-engine-bullseye-stable/InRelease  Splitting up /var/lib/apt/lists/packages.cloud.google.com_apt_dists_google-compute-engine-bullseye-stable_InRelease into data and signature failed
W: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk-bullseye/InRelease  Splitting up /var/lib/apt/lists/packages.cloud.google.com_apt_dists_cloud-sdk-bullseye_InRelease into data and signature failed
W: Some index files failed to download. They have been ignored, or old ones used instead.
+ sh -c 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null'
E: You don't have enough free space in /var/cache/apt/archives/.
Failed to enable unit: Unit file docker.service does not exist.
Failed to start docker.service: Unit docker.service not found.
docker installation failed, please check your environment

**Comment by enwaiax** [comment]
Failed to install docker due to error **E: You don't have enough free space in /var/cache/apt/archives/.**

**Comment by xingpingcn** [comment]
> Failed to install docker due to error **E: You don't have enough free space in /var/cache/apt/archives/.**

但这是一个新是实例，我是直接运行交互命令的，在他创建了Swap之后就会填满vm的硬盘空间，所以创建docker会提示空间不足，但是在亚马逊云上就没有这个问题。

**Comment by enwaiax** [comment]
Fixed in bb1ec7d0fc826d4bdb49d522a84e4c22ff3d25ae

新创建一台，重新试一下

**Comment by xingpingcn** [comment]
> Fixed in [bb1ec7d](https://github.com/Chasing66/peer2profit/commit/bb1ec7d0fc826d4bdb49d522a84e4c22ff3d25ae)
> 
> 新创建一台，重新试一下

done. it works on gcp now.
