### ISSUE TITLE
Doesn't work when trying to install as service on Ubuntu server 20.04

### ISSUE THREAD

**Issue by mrwrenchy** [Chasing66/peer2profit#30]
bash <(curl -fsSL git.io/JzDdQ) email redracted
Installing dependencies...
Installing p2pclient...
--2023-12-03 18:48:09--  https://updates.peer2profit.app/peer2profit_0.48_amd64.deb
Resolving updates.peer2profit.app (updates.peer2profit.app)... 178.32.99.172
Connecting to updates.peer2profit.app (updates.peer2profit.app)|178.32.99.172|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10381318 (9.9M) [application/octet-stream]
Saving to: ‘p2pclient.deb’

p2pclient.deb                         100%[=======================================================================>]   9.90M  35.2MB/s    in 0.3s    

2023-12-03 18:48:09 (35.2 MB/s) - ‘p2pclient.deb’ saved [10381318/10381318]

Selecting previously unselected package peer2profit.
(Reading database ... 113633 files and directories currently installed.)
Preparing to unpack p2pclient.deb ...
Unpacking peer2profit (0.48) ...
dpkg: dependency problems prevent configuration of peer2profit:
 peer2profit depends on libxcb-icccm4; however:
  Package libxcb-icccm4 is not installed.
 peer2profit depends on libxcb-image0; however:
  Package libxcb-image0 is not installed.
 peer2profit depends on libxcb-keysyms1; however:
  Package libxcb-keysyms1 is not installed.
 peer2profit depends on libxcb-render-util0; however:
  Package libxcb-render-util0 is not installed.
 peer2profit depends on libxcb-render0; however:
  Package libxcb-render0 is not installed.
 peer2profit depends on libxcb-xinerama0; however:
  Package libxcb-xinerama0 is not installed.
 peer2profit depends on libxcb-xkb1; however:
  Package libxcb-xkb1 is not installed.
 peer2profit depends on libxkbcommon-x11-0; however:
  Package libxkbcommon-x11-0 is not installed.
 peer2profit depends on libxkbcommon0; however:
  Package libxkbcommon0 is not installed.
 peer2profit depends on libxcb-util1; however:
  Package libxcb-util1 is not installed.

dpkg: error processing package peer2profit (--install):
 dependency problems - leaving unconfigured
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 peer2profit
Starting peer2profit...
Created symlink /etc/systemd/system/multi-user.target.wants/peer2profit.service → /etc/systemd/system/peer2profit.service.
● peer2profit.service - peer2profit
     Loaded: loaded (/etc/systemd/system/peer2profit.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2023-12-03 18:48:14 UTC; 25ms ago
    Process: 3325947 ExecStart=/usr/bin/p2pclient -l [email and ip address];8.8.8.8,1.1.1.1 (code=exited, status=203/EXEC)
   Main PID: 3325947 (code=exited, status=203/EXEC)

**Comment by enwaiax** [comment]
@mrwrenchy Yes, it's no longer supported to installed as service.
