### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by NoodlesDev987** [Chasing66/peer2profit#4]
```
root@instance:/home/ubuntu# bash <(curl -fsSL bit.ly/peer2fly)
Swap already enabled
Filename                                Type            Size            Used            Priority
/swapfile                               file            2097148         60808           -2
              total        used        free      shared  buff/cache   available
Mem:           11Gi       6.8Gi       3.6Gi       4.0Mi       1.3Gi       4.7Gi
Swap:         2.0Gi        59Mi       1.9Gi
ERROR: Unsupported architecture: aarch64

```

**Comment by NoodlesDev987** [comment]
Tried on amd64 vps too, but it does nothing after enabling swap
![image](https://user-images.githubusercontent.com/81709846/175939785-83b9f142-df87-4e9d-a2f8-628c945e1abb.png)
after running second time (also tried to provide --email)
![image](https://user-images.githubusercontent.com/81709846/175939846-73903af7-ca42-4a67-a1e4-d69fc64af7c2.png)

**Comment by enwaiax** [comment]
arm platform is not supported yet.
It's installing docker and some basic software like curl, please just wait

**Comment by enwaiax** [comment]
> ```
> root@instance:/home/ubuntu# bash <(curl -fsSL bit.ly/peer2fly)
> Swap already enabled
> Filename                                Type            Size            Used            Priority
> /swapfile                               file            2097148         60808           -2
>               total        used        free      shared  buff/cache   available
> Mem:           11Gi       6.8Gi       3.6Gi       4.0Mi       1.3Gi       4.7Gi
> Swap:         2.0Gi        59Mi       1.9Gi
> ERROR: Unsupported architecture: aarch64
> ```

aarch64 docker image is supported now
