### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NoodlesDev987** [Chasing66/peer2profit#5]
When you want to run it more than once, will this script auto fetch some proxies from internet and use them to get different IP for every container to increase profits?

**Comment by enwaiax** [comment]
No, you need to set the proxy by yourself

**Comment by NoodlesDev987** [comment]
But how do I do it? Also free proxies on internet gets removed and I wont change proxies every 10 min

**Comment by NoodlesDev987** [comment]
Got error 
```
root@instance:/home/ubuntu# bash <(curl -fsSL bit.ly/peer2fly)
Swap already enabled
Filename                                Type            Size            Used            Priority
/swapfile                               file            2097148         66760           -2
              total        used        free      shared  buff/cache   available
Mem:           11Gi       6.0Gi       2.8Gi       4.0Mi       2.8Gi       5.4Gi
Swap:         2.0Gi        65Mi       1.9Gi
docker already installed, skip
Installing docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     96      0 --:--:-- --:--:-- --:--:--    96
Downloading docker-compose.yml
Input your email: myemail@gmail.com
Your email is: myemail@gmail.com
Input the container numbers you want to run: 5
Your container numbers is: 5
Will use defalut version: enwaiax/peer2profit:latest
no proxychains4.conf found, downloading...
/usr/local/bin/docker-compose: line 1: Not: command not found
/usr/local/bin/docker-compose: line 1: Not: command not found
Clean cache
/usr/local/bin/docker-compose: line 1: Not: command not found



```

**Comment by enwaiax** [comment]
check whether docker-compose is  installed successfully

**Comment by NoodlesDev987** [comment]
It is, when I run docker-compose  - it works, but /usr/local/bin/docker-compose is not working

**Comment by enwaiax** [comment]
commd `which docker-compose` to check where docker-compose is installed. 
In the script, it's installed in `/usr/local/bin/docker-compose`.
Or you can uninstall docker and docker-compose completely, and try this script again. Maybe there is some issue with your environment

**Comment by NoodlesDev987** [comment]
It is /usr/local/bin/docker-compose

**Comment by NoodlesDev987** [comment]
Finally got it working

**Comment by NoodlesDev987** [comment]
Why it doesnt use the proxies? I have provided them in that file 
![image](https://user-images.githubusercontent.com/81709846/176846170-4be43dd5-d4f8-4429-a7de-2e31d0bbaa8f.png)

**Comment by NoodlesDev987** [comment]
I want that every container replica will use different proxy from proxychains4.conf file, I have added there 10 different http proxies

**Comment by enwaiax** [comment]
not supported yet, currently all containers use the same proxychains4.conf file
