### ISSUE TITLE
Auto fetch proxies every 30 min from link

### ISSUE THREAD

**Issue by NoodlesDev987** [Chasing66/peer2profit#6]
Add option that you can provide link and it will auto fetch proxies from it every 30 min (or make it be custom interval) and on start. So you can make gist file with proxies and update it when you get new proxies

**Comment by enwaiax** [comment]
I suppose I will not develop this feature sicne if you want stable trafic you should try stable proxy, especially for this pee2profit which residential IP is better. Actually the proxy function is used to apply the residential proxy on the IDC VPS to make you run more instance.
