### ISSUE TITLE
p2pclient not available anymore

### ISSUE THREAD

**Issue by uhliksk** [Chasing66/peer2profit#7]
The download link to p2pclient_0.60_amd64.deb is not working anymore. Is there any workaround to run this version of software?

**Comment by enwaiax** [comment]
> The download link to p2pclient_0.60_amd64.deb is not working anymore. Is there any workaround to run this version of software?

The Peer2profit official updated the URL. 
Check the latest [commit](https://github.com/Chasing66/peer2profit/commit/6c943f9a61775d90c92ab7e4fcbcf10c543c5576) and try.
